DEMO_HOLDINGS = [
    {
        "ticker": "AAPL",
        "name": "Apple Inc.",
        "type": "equity",
        "shares": 12,
        "price": 200,
        "value": 2400,
        "sector": "Technology",
        "simulated_metrics": {
            "ticker": "AAPL",
            "pe_ratio": 29,
            "eps": 7.1,
            "revenue_growth": 8,
            "eps_growth": 10,
            "profit_margin": 24,
            "return_on_equity": 45,
            "current_ratio": 1.1,
            "beta": 1.2,
            "52_week_return": 12,
        },
    },
    {
        "ticker": "MSFT",
        "name": "Microsoft Corporation",
        "type": "equity",
        "shares": 5,
        "price": 420,
        "value": 2100,
        "sector": "Technology",
        "simulated_metrics": {
            "ticker": "MSFT",
            "pe_ratio": 32,
            "eps": 14,
            "revenue_growth": 14,
            "eps_growth": 16,
            "profit_margin": 35,
            "return_on_equity": 38,
            "current_ratio": 1.4,
            "beta": 0.9,
            "52_week_return": 18,
        },
    },
    {
        "ticker": "VTI",
        "name": "Sample Total Market ETF",
        "type": "etf",
        "shares": 8,
        "price": 275,
        "value": 2200,
    },
    {
        "ticker": None,
        "name": "Sample Cash Balance",
        "type": "cash",
        "shares": 1,
        "price": 1300,
        "value": 1300,
    },
]
